# Welcome to Jekyll!

# Website settings
title: "Eliot"
description: "Eliot's blog power by Jekyll and github pages."
keywords: "Eliot,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://billeliot.github.io"

# blog img path
img_path: 'static/img/blog'

# author
author:
  name: 'Eliot'
  first_name: 'Jiaze'
  last_name: 'Wu'
  email: '1161142536@qq.com'
  facebook_username: ''
  github_username: 'BillEliot'
  head_img: 'static/img/landing/WJZ.jpg'

# social link
jingyu:
  first_name: 'Yu'
  last_name: 'Jing'
  description: 'Painter.'
  link: 'http://angular.jack003.com'
  email: '805963294@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'C/C++'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/C++.png'
  jalpc:
    name: 'Python'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/Python.png'
  angularjs:
    name: 'Linux/Shell'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/Linux.png'
  Rsser:
    name: 'Unity3D'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/Unity3D.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'C/C++'
  mac: 'Unity3D'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
